n="lillygrace"
print(n.upper())
print(n.lower())
print(n.capitalize())
print(n.title())
print(n.swapcase())
print(n.strip())
print(n.lstrip())
print(n.rstrip())
print(n.replace( "lillygrace","sharonroja"))
print(n.count("r"))
print(n.find("a"))
print(n.index("a"))
print(n.startswith("l"))
print(n.endswith("e"))
print(n.isalpha())